# Change these first
owner: redjoker011 # Your GitHub username
repo: cg-upptime-monitoring # Your Github repository name

# Add your sites here
sites:
  - name: ChatGenie CMS
    url: https://www.chatgenie.ph
  - name: ChatGenie Mini App
    url: $CG_MINI_APP_URL
  - name: ChatGenie API
    url: $CG_API_URL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /cg-upptime-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**ChatGenie** Uptime Monitoring"
  introMessage: Monitor Server Host Uptime. Powered by [Upptime](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
